vich_uploader:
    db_driver: orm

    metadata:
            type: attribute

    mappings:
        estates:
            uri_prefix: /uploads/estate
            upload_destination: '%kernel.project_dir%/public/uploads/estate'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer